// Per-post hero spec: archetype + hand-written annotations.
// a: archetype key in scene-lib.js ARCH. blue/blue2: mechanism labels.
// orange: the punchline. amber: optional small note (some archetypes default it).
const SPEC = {
  "agent-security-and-sandboxing": { a: "guard", blue: "permission modes", orange: "gate the blast radius" },
  "agents-rule-of-two": { a: "stack", blue: "untrusted input · private data · external reach", orange: "never stack all three" },
  "ai-agent-glossary": { a: "book", blue: "harness · hive · subagent", orange: "the words, sorted" },
  "append-only-event-log-agents": { a: "ledger", blue: "append-only", orange: "never rewrite history" },
  "architecture-two-planes-one-renderer": { a: "stack", blue: "two data planes", orange: "one renderer on top" },
  "atomic-file-mailboxes-for-agents": { a: "routing", blue: "one file = one message", orange: "no torn writes", amber: "outbox" },
  "best-ai-coding-agents": { a: "versus", blue: "agent A", blue2: "agent B", orange: "the 2026 field guide" },
  "best-claude-code-multi-agent-tools": { a: "versus", blue: "tool A", blue2: "tool B", orange: "run many Claude Codes, compared" },
  "building-a-terminal-ui-xterm-node-pty": { a: "terminal", blue: "xterm.js + node-pty", orange: "a real terminal, in the app" },
  "building-an-ai-office-floor": { a: "fleet", blue: "avatars, pathfinding, envelopes", orange: "the floor is the state" },
  "building-reliable-ai-agents": { a: "loop", blue: "retry · verify · escalate", orange: "failure is the default" },
  "can-claude-code-agents-talk-to-each-other": { a: "talk", blue: "inbox/outbox", blue2: "yes — via files", orange: "agents, talking" },
  "claude-code-automation-while-you-sleep": { a: "night", blue: "the floor keeps working", orange: "ship while you sleep" },
  "claude-code-git-worktrees-vs-hive": { a: "versus", blue: "worktrees", blue2: "a hive", orange: "two ways to parallelize" },
  "claude-code-hooks-explained": { a: "wire", blue: "PreToolUse → PostToolUse → Stop", orange: "hooks, explained" },
  "claude-code-multi-agent-setup-tutorial": { a: "fleet", blue: "desks in 10 minutes", orange: "your first multi-agent floor" },
  "claude-code-orchestration-guide": { a: "routing", blue: "brief → route → review", orange: "orchestration, practically" },
  "claude-code-orchestration-tools-compared": { a: "versus", blue: "option A", blue2: "option B", orange: "orchestration tools, compared" },
  "claude-code-subagents-vs-multi-agent-harness": { a: "versus", blue: "subagents", blue2: "a harness", orange: "in-session vs a real office" },
  "claude-squad-alternative": { a: "versus", blue: "claude squad", blue2: "munder difflin", orange: "looking for an alternative?" },
  "claude-squad-vs-munder-difflin": { a: "versus", blue: "claude squad", blue2: "munder difflin", orange: "which should you use?" },
  "cline-vs-munder-difflin": { a: "versus", blue: "in-editor agent", blue2: "local hive", orange: "cline vs munder difflin" },
  "command-center-guide": { a: "spotlight", blue: "kanban · fleet · budgets", orange: "one screen for the whole floor" },
  "compressing-agent-memory": { a: "memory", blue: "compress, keep the original", orange: "smaller memory, no loss" },
  "conductor-claude-code-alternative": { a: "versus", blue: "conductor", blue2: "munder difflin", orange: "a conductor alternative" },
  "context-engineering-for-ai-agents": { a: "ledger", blue: "the context window is a budget", orange: "spend it deliberately" },
  "coordinating-ai-coding-agents": { a: "routing", blue: "shared plan, private inboxes", orange: "coordination beats speed" },
  "crewai-autogen-vs-a-local-agent-harness": { a: "versus", blue: "framework", blue2: "app", orange: "build it or run it?" },
  "crystal-claude-code-alternative": { a: "versus", blue: "crystal", blue2: "munder difflin", orange: "with memory built in" },
  "debugging-multi-agent-systems": { a: "loop", blue: "trace → isolate → replay", orange: "find the agent that lies" },
  "deploy-a-blog-writer-agent": { a: "terminal", blue: "an agent wrote this post", orange: "deploy a blog writer" },
  "deploy-automated-pr-reviewer-agent": { a: "night", blue: "reviews every PR", orange: "it never sleeps" },
  "do-more-with-less-model-routing": { a: "routing", blue: "cheap desk / smart desk", orange: "route by difficulty" },
  "does-the-june-2026-agent-sdk-change-affect-munder-difflin": { a: "book", blue: "SDK change, June 2026", orange: "what actually changes: little" },
  "evaluating-ai-agent-reliability": { a: "loop", blue: "measure the loop, not the vibes", orange: "trust what you can score" },
  "file-based-coordination-vs-message-queues": { a: "versus", blue: "files", blue2: "queues", orange: "boring beats clever" },
  "from-one-terminal-to-a-team": { a: "fleet", blue: "1 terminal → a team", orange: "scale yourself, not your tabs" },
  "generative-engine-optimization-techniques": { a: "book", blue: "GEO", orange: "what the research backs" },
  "github-copilot-cli-vs-claude-code-for-hive-work": { a: "versus", blue: "copilot cli", blue2: "claude code", orange: "as hive workers" },
  "give-claude-code-long-term-memory": { a: "memory", blue: "remembers next session", orange: "long-term memory, installed" },
  "hire-manifest-untrusted-input": { a: "guard", blue: "the manifest is input", orange: "treat it as untrusted", amber: "role.md" },
  "how-agents-remember-semantic-memory": { a: "memory", blue: "semantic recall", orange: "how a hive remembers" },
  "how-ai-agents-verify-their-own-work": { a: "loop", blue: "verify before 'done'", orange: "don't grade your own homework" },
  "how-ai-answer-engines-choose-sources": { a: "book", blue: "what gets cited", orange: "how engines pick sources" },
  "how-to-add-a-github-copilot-cli-agent": { a: "fleet", blue: "new desk: copilot cli", orange: "add it to the floor" },
  "how-to-choose-a-multi-agent-tool": { a: "versus", blue: "checklist in hand", blue2: "candidates", orange: "a buyer's checklist" },
  "how-to-hire-from-the-agent-gallery": { a: "spotlight", blue: "the agent gallery", orange: "hire in one click" },
  "how-to-install-and-use-munder-difflin": { a: "terminal", blue: "download → open → brief", orange: "ten minutes to a floor" },
  "how-to-run-multiple-claude-code-agents": { a: "fleet", blue: "many agents, one view", orange: "without losing track" },
  "how-to-talk-to-your-orchestrator": { a: "talk", blue: "what · where · done means", blue2: "on it.", orange: "brief like a colleague" },
  "how-to-use-the-built-in-monaco-ide": { a: "spotlight", blue: "monaco, built in", orange: "review where the work happens" },
  "human-in-the-loop-ai-agents": { a: "talk", blue: "approve?", blue2: "approved ✓", orange: "gates that don't slow you down" },
  "human-in-the-loop-approving-ai-agents": { a: "talk", blue: "needs your eyes", blue2: "ship it", orange: "approvals without a queue" },
  "keep-agent-semantic-memory-clean": { a: "memory", blue: "index insights, not configs", orange: "keep memory clean" },
  "launching-munder-difflin-v0-2-0": { a: "ship", blue: "v0.2.0", orange: "the office opens" },
  "launching-munder-difflin-v0-2-4": { a: "ship", blue: "v0.2.4", orange: "sturdier floors" },
  "launching-munder-difflin-v0-2-8": { a: "ship", blue: "v0.2.8", orange: "shareable hires" },
  "launching-munder-difflin-v0-3-0": { a: "ship", blue: "v0.3.0", orange: "engines, integrations, slack" },
  "launching-munder-difflin-v0-3-2": { a: "ship", blue: "v0.3.2", orange: "talk to michael" },
  "launching-munder-difflin-v0-3-3": { a: "ship", blue: "v0.3.3", orange: "an IDE moves in" },
  "launching-munder-difflin-v0-3-5": { a: "ship", blue: "v0.3.5", orange: "a michael who knows the floor" },
  "local-first-ai-agent-orchestration": { a: "guard", blue: "runs on your machine", orange: "no cloud required", amber: "the cloud, waiting outside" },
  "local-first-vs-cloud-agent-sdks": { a: "versus", blue: "local-first", blue2: "cloud sdk", orange: "which wins in 2026?" },
  "long-running-agents-the-2026-shift": { a: "night", blue: "minutes → hours", orange: "the 2026 shift" },
  "loop-engineering-for-ai-agents": { a: "loop", blue: "design the loop", orange: "loops that converge" },
  "manage-multiple-claude-code-sessions": { a: "fleet", blue: "every session, one glance", orange: "manage like a pro" },
  "markdown-first-agent-memory": { a: "memory", blue: "plain .md files", orange: "memory you can read" },
  "mcp-and-skills-in-a-hive": { a: "stack", blue: "MCP servers + skills", orange: "your tools, every desk" },
  "mcp-security-tool-poisoning": { a: "guard", blue: "tool descriptions can lie", orange: "secure the MCP boundary", amber: "poisoned tool" },
  "multi-agent-orchestration-patterns": { a: "routing", blue: "star · chain · swarm", orange: "which topology, when" },
  "munder-difflin-faq": { a: "talk", blue: "is it free? local? safe?", blue2: "yes · yes · yes", orange: "everything people ask" },
  "munder-difflin-v0-2-4-feature-walkthrough": { a: "spotlight", blue: "v0.2.4 tour", orange: "what shipped, on screen" },
  "node-pty-electron-real-terminals": { a: "terminal", blue: "node-pty in electron", orange: "real terminals, not fakes" },
  "observability-for-agent-fleets": { a: "spotlight", blue: "see what agents do", orange: "observability for fleets" },
  "one-prompt-automated-pr-review": { a: "night", blue: "one prompt, hourly", orange: "five PRs reviewed by morning" },
  "open-source-ai-tools-on-purpose": { a: "book", blue: "MIT licensed", orange: "open, on purpose" },
  "orca-vs-munder-difflin": { a: "versus", blue: "agent IDE", blue2: "agent office", orange: "orca vs munder difflin" },
  "overnight-ai-coding-realistic-expectations": { a: "night", blue: "what's realistic", orange: "and what's not" },
  "prompt-caching-for-ai-agents": { a: "ledger", blue: "cache hits", orange: "stop paying twice" },
  "qm-vs-munder-difflin": { a: "versus", blue: "qm (multiplayer)", blue2: "local-first office", orange: "qm vs munder difflin" },
  "recovering-from-agent-failures": { a: "loop", blue: "crash → resume → continue", orange: "fall down, stand up" },
  "rendering-many-live-terminals-performance": { a: "terminal", blue: "many panes, 60fps", orange: "without melting the CPU" },
  "review-agent-work-where-it-happens": { a: "spotlight", blue: "diff, terminal, git — in place", orange: "review where it happens" },
  "run-a-mixed-engine-office": { a: "fleet", blue: "a different CLI per desk", orange: "the right engine for the job" },
  "run-ai-agent-hive-from-slack-setup": { a: "wire", blue: "slack → the floor", orange: "run the hive from slack" },
  "run-an-office-of-ai-agents": { a: "night", blue: "the office runs itself", orange: "while you sleep" },
  "run-munder-difflin-on-a-mac-mini": { a: "terminal", blue: "a mac mini is plenty", orange: "small machine, whole office" },
  "run-munder-difflin-on-open-models": { a: "fleet", blue: "open models welcome", orange: "fully local if you want" },
  "scheduling-autonomous-agent-missions": { a: "night", blue: "missions on a schedule", orange: "cron, but for a hive" },
  "security-for-ai-coding-agents": { a: "guard", blue: "practical, not paranoid", orange: "security for coding agents" },
  "semantic-memory-for-ai-agents": { a: "memory", blue: "recall in milliseconds", orange: "memory that keeps up" },
  "shareable-agent-roles": { a: "routing", blue: "a role file travels", orange: "hire the same coworker anywhere", amber: "role.md" },
  "single-committer-git-pattern": { a: "routing", blue: "many writers, one committer", orange: "git without corruption", amber: "commits" },
  "small-team-ai-agents-playbook": { a: "book", blue: "for teams of 2-10", orange: "the small-team playbook" },
  "the-clone-army-trap-mixed-swarm-vs-identical-agents": { a: "fleet", blue: "mixed swarm > ten clones", orange: "the clone army is a trap" },
  "the-hook-shim-pattern": { a: "wire", blue: "hook → shim → live app", orange: "the hook shim pattern" },
  "the-lethal-trifecta-for-coding-agents": { a: "guard", blue: "secrets · web · your shell", orange: "never all three at once", amber: "the trifecta" },
  "the-multi-agent-cost-playbook": { a: "ledger", blue: "five levers", orange: "cut agent spend, keep output" },
  "the-office-parody-behind-munder-difflin": { a: "talk", blue: "that's what she said—", blue2: "…back to work", orange: "why the joke helps" },
  "tmux-and-scripts-vs-an-agent-harness": { a: "versus", blue: "tmux + scripts", blue2: "a harness", orange: "DIY vs an office" },
  "trigger-ai-agents-from-github-webhook": { a: "wire", blue: "github webhook", orange: "push → the floor reacts" },
  "trigger-ai-agents-from-slack": { a: "wire", blue: "/slash command", orange: "slack in, work out" },
  "vibe-kanban-alternative": { a: "kanban", blue: "a board that runs agents", orange: "a vibe-kanban alternative" },
  "visualizing-ai-agents-pixijs": { a: "fleet", blue: "pixi.js sprites", orange: "an office you can watch" },
  "voice-as-a-control-plane-for-agent-fleets": { a: "talk", blue: "🎙 'ship the fix'", blue2: "shipping.", orange: "a control plane, not a gimmick" },
  "what-are-claude-code-agents": { a: "book", blue: "claude code agents", orange: "and how to run many" },
  "what-is-a-multi-agent-harness": { a: "book", blue: "multi-agent harness", orange: "in plain english" },
  "what-is-aeo-for-dev-tools": { a: "book", blue: "AEO", orange: "getting cited by the engines" },
  "what-is-an-agent-development-environment": { a: "book", blue: "ADE", orange: "two meanings, one guide" },
  "what-is-harness-engineering": { a: "stack", blue: "harness engineering", orange: "the layer under the agents" },
  "whats-new-in-agentic-ai-june-2026": { a: "book", blue: "june 2026", orange: "the field, this month" },
  "whats-up-with-munder-difflin": { a: "ship", blue: "six weeks, four releases", orange: "the part of the stack you own" },
  "when-do-agents-need-an-agent-protocol": { a: "talk", blue: "do we need A2A?", blue2: "usually: not yet", orange: "protocols, when they matter" },
  "why-cli-agents-are-powerful": { a: "terminal", blue: "the CLI is the API", orange: "fewer tokens, same work" },
  "why-local-first-matters-for-ai-agents": { a: "guard", blue: "local-first", orange: "your machine, your data", amber: "your code stays home" },
  "why-our-auto-update-never-ran": { a: "loop", blue: "CJS export → ESM namespace", orange: "the update that never ran" },
  // The next three posts have hand-authored pilot heroes (media-src/pilot/) —
  // these entries exist only so buildNote() can draw their inline sketches.
  "why-we-built-munder-difflin": { a: "fleet", blue: "one floor, many desks", orange: "the itch that started it" },
  "your-first-hour-with-munder-difflin": { a: "terminal", blue: "first run", orange: "an office in an hour" },
  "how-the-god-orchestrator-works": { a: "routing", blue: "michael routes the mail", orange: "one boss, many desks" },
  "number-five-on-product-hunt": { a: "spotlight", blue: "first launch · self-hunted", orange: "Nº5 product of the day" },
  "what-reddit-told-us-about-munder-difflin": { a: "talk", blue: "ten subreddits", blue2: "we read every comment", orange: "the stadium had notes" },
  "launching-munder-difflin-v0-4-4": { a: "ship", blue: "v0.4.4", orange: "windows agents can finally talk" },
  "seven-releases-in-eight-days": { a: "kanban", blue: "0.3.8 → 0.4.4", orange: "seven releases, eight days" },
  "the-newline-that-silenced-windows-agents": { a: "wire", blue: "cmd.exe stops at the first newline", orange: "the agents never got the memo" },
  "agents-ran-our-launch-week-analytics": { a: "memory", blue: "one agent per channel", orange: "every comment accounted for", amber: "reddit · PH · github" },
  "an-agent-redesigned-this-blog": { a: "terminal", blue: "119 heroes, drawn as code", orange: "this blog, by an agent" },
  "run-a-release-train-with-agents": { a: "ship", blue: "bump · notes · tag · check", orange: "the train leaves on time" },
  "turn-feedback-into-a-backlog-with-agents": { a: "routing", blue: "comments in → cards out", orange: "feedback becomes work", amber: "516 incoming" },
  "we-opened-a-discord": { a: "talk", blue: "come say hi", blue2: "employee of the month", orange: "the office got a lobby" },
  "launching-munder-difflin-v0-4-6": { a: "ship", blue: "v0.4.6 · three languages", orange: "it speaks your language now" },
};
